name: lost_dart
version: 0.4.0+m3
description: >
  Lost Dart is Inversion of Control Container implementation for Dart.
authors:
- Sergey Akopkokhyants <akserg@gmail.com>
homepage: http://www.lostdart.com
dependencies:
  unittest: ">=0.3.1+1"
  browser: ">=0.3.1+1"
