name: lost_dart
version: 0.4.4
description: >
  Lost Dart is Inversion of Control Container implementation for Dart.
authors:
- Sergey Akopkokhyants <akserg@gmail.com>
homepage: http://www.lostdart.com
dependencies:
  unittest: ">=0.4.0"
  browser: ">=0.4.0"
