name: lost_dart
version: 0.5.3
author: Sergey Akopkokhyants <akserg@gmail.com>
description: Lost Dart is Inversion of Control Container implementation for Dart.
homepage: http://www.lostdart.com
dependencies:
  unittest: '>=0.6.21'
