name: lost_dart
version: 1.0.7
author: Sergey Akopkokhyants <akserg@gmail.com>
description: Lost Dart is Inversion of Control Container implementation for Dart.
homepage: http://www.lostdart.com
environment:
  sdk: '>=1.6.0 <2.0.0'
dev_dependencies:
  unittest: '>=0.11.5 <2.0.0'
