name: lost_dart
version: 1.0.4
author: Sergey Akopkokhyants <akserg@gmail.com>
description: Lost Dart is Inversion of Control Container implementation for Dart.
homepage: http://www.lostdart.com
environment:
  sdk: '>=1.3.3 <2.0.0'
dev_dependencies:
  unittest: '>=0.10.1+2 <2.0.0'
